identifier: CVE-2017-7233
title: Open redirect and possible XSS attack via user-supplied numeric redirect URLs
description: "Django relies on user input in some cases (e.g. `django.contrib.auth.views.login()`
  and i18n) to redirect the user to an \"on success\" URL. The security check for
  these redirects (namely `django.utils.http.is_safe_url()`) considered some numeric
  URLs (e.g. http:999999999) \"safe\" when they shouldn't be.\r\n\r\nAlso, if a developer
  relies on `is_safe_url()` to provide safe redirect targets and puts such a URL into
  a link, they could suffer from an XSS attack."
date: "2017-04-04"
affected_range: '>=1.11alpha,<1.11||>=1.10.0alpha,<1.10.7||>=1.9.0alpha,<1.9.13||<1.8.18'
fixed_versions:
- 1.10.7
- "1.11"
- 1.8.18
- 1.9.13
affected_versions: All versions
solution: Upgrade to latest version
urls:
- https://www.djangoproject.com/weblog/2017/apr/04/security-releases/
uuid: 3ee25254-38af-494e-9fb9-5e3389d0dcfb
package_slug: pypi/Django
