---
identifier: "CVE-2018-14574"
identifiers:
- "GHSA-5hg3-6c2f-f3wr"
- "CVE-2018-14574"
package_slug: "pypi/django"
title: "URL Redirection to Untrusted Site ('Open Redirect')"
description: "django.middleware.common.CommonMiddleware in Django has an Open Redirect."
date: "2021-09-01"
pubdate: "2018-10-04"
affected_range: ">=1.11.0,<1.11.15||>=2.0,<2.0.8"
fixed_versions:
- "1.11.15"
- "2.0.8"
affected_versions: "All versions starting from 1.11.0 before 1.11.15, all versions
  starting from 2.0 before 2.0.8"
not_impacted: "All versions before 1.11.0, all versions starting from 1.11.15 before
  2.0, all versions starting from 2.0.8"
solution: "Upgrade to versions 1.11.15, 2.0.8 or above."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2018-14574"
- "https://access.redhat.com/errata/RHSA-2019:0265"
- "https://github.com/advisories/GHSA-5hg3-6c2f-f3wr"
- "https://usn.ubuntu.com/3726-1/"
- "https://www.debian.org/security/2018/dsa-4264"
- "https://www.djangoproject.com/weblog/2018/aug/01/security-releases/"
- "http://www.securityfocus.com/bid/104970"
- "http://www.securitytracker.com/id/1041403"
cvss_v2: "AV:N/AC:M/Au:N/C:P/I:P/A:N"
cvss_v3: "CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N"
uuid: "680b6d3c-0665-44f1-845f-00c1e49a3740"
cwe_ids:
- "CWE-1035"
- "CWE-601"
- "CWE-937"
