source_identifier: CVE-2016-9015
title: Certificate verification failure
description: The library suffer from a vulnerability that can cause them, in certain
  configurations, to not correctly validate TLS certificates. This places users of
  the library with those configurations at risk of man-in-the-middle and information
  leakage attacks.
date: "2016-10-27"
affected_range: '>=1.17,<1.18.1'
fixed_versions:
- 1.18.1
affected_versions: 1.17, 1.18
not_impacted: 1.16 and earlier
solution: Affected users should upgrade to urllib3 1.18.1, which has been published
  today and contains only the mitigation for this vulnerability on top of the changes
  in 1.18. If unable to upgrade, users should downgrade their OpenSSL version or temporarily
  stop injecting PyOpenSSL into urllib3 until they are able to upgrade.
urls:
- http://seclists.org/oss-sec/2016/q4/256
- https://github.com/openssl/openssl/pull/1793
uuid: 1b9f2542-73f0-45b6-ad5e-04f035c5655b
package_slug: pypi/urllib3
