---
identifier: CVE-2019-1010142
package_slug: pypi/scapy
title: Uncontrolled Resource Consumption
description: 'scapy is affected by a Denial of Service vulnerability. The impact is: infinite
  loop, resource consumption and program unresponsive. The component is: _RADIUSAttrPacketListField.getfield(self..).
  The attack vector is: over the network or in a pcap. both work.'
date: '2019-07-23'
affected_range: "==2.4.0"
fixed_versions:
- 2.4.1
affected_versions: Version 2.4.0
not_impacted: All versions before 2.4.0, all versions after 2.4.0
solution: Upgrade to version 2.4.1 or above.
credit: ''
urls:
- https://nvd.nist.gov/vuln/detail/CVE-2019-1010142
- https://pypi.python.org/pypi/scapy
uuid: bc7285f1-4685-4515-88e3-686691d9423f
