---
identifier: "CVE-2022-33124"
identifiers:
- "GHSA-rwqr-c348-m5wr"
- "CVE-2022-33124"
package_slug: "pypi/aiohttp"
title: "Denial of Service in aiohttp"
description: "** DISPUTED ** AIOHTTP 3.8.1 can report a \"ValueError: Invalid IPv6
  URL\" outcome, which can lead to a Denial of Service (DoS). NOTE: multiple third
  parties dispute this issue because there is no example of a context in which denial
  of service would occur, and many common contexts have exception handing in the calling
  application."
date: "2022-06-25"
pubdate: "2022-06-24"
affected_range: "<=3.8.1"
fixed_versions: []
affected_versions: "All versions up to 3.8.1"
not_impacted: ""
solution: "Unfortunately, there is no solution available yet."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2022-33124"
- "https://github.com/aio-libs/aiohttp/issues/6772"
- "https://github.com/advisories/GHSA-rwqr-c348-m5wr"
uuid: "e351f0d9-5c91-4e20-80d6-7644e21bd00c"
cwe_ids:
- "CWE-1035"
- "CWE-937"
