---
identifier: "CVE-2021-37681"
package_slug: "pypi/tensorflow"
title: "NULL Pointer Dereference"
description: "TensorFlow is an end-to-end open source platform for machine learning.
  The [`GetVariableInput` function](https://github.com/tensorflow/tensorflow/blob/460e000de3a83278fb00b61a16d161b1964f15f4/tensorflow/lite/kernels/kernel_util.cc#L115-L119)
  can return a null pointer but `GetTensorData` assumes that the argument is always
  a valid tensor. Furthermore, because `GetVariableInput` calls [`GetMutableInput`](https://github.com/tensorflow/tensorflow/blob/460e000de3a83278fb00b61a16d161b1964f15f4/tensorflow/lite/kernels/kernel_util.cc#L82-L90)
  which might return `nullptr`, the `tensor->is_variable` expression can also trigger
  a null pointer exception. We have patched the issue in GitHub commit 5b048e87e4e55990dae6b547add4dae59f4e1c76.
  The fix will be included in TensorFlow We will also cherrypick this commit on TensorFlow,
  TensorFlow, and TensorFlow, as these are also affected and still in supported range."
date: "2021-08-18"
pubdate: "2021-08-12"
affected_range: ">=2.3.0,<2.3.4||>=2.4.0,<2.4.3||>=2.5.0,<=2.6.0"
fixed_versions:
- "2.3.4"
- "2.4.3"
affected_versions: "All versions starting from 2.3.0 before 2.3.4, all versions starting
  from 2.4.0 before 2.4.3, all versions starting from 2.5.0 up to 2.6.0"
not_impacted: "All versions before 2.3.0, all versions starting from 2.3.4 before
  2.4.0, all versions starting from 2.4.3 before 2.5.0, all versions after 2.6.0"
solution: "Upgrade to versions 2.3.4, 2.4.3 or above."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2021-37681"
cvss_v2: "AV:L/AC:L/Au:N/C:P/I:P/A:P"
cvss_v3: "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H"
uuid: "8b4b0889-a2a4-4689-ac07-9240157c0928"
