---
identifier: "CVE-2021-37644"
package_slug: "pypi/tensorflow"
title: "Reachable Assertion"
description: "TensorFlow is an end-to-end open source platform for machine learning.
  The [implementation](https://github.com/tensorflow/tensorflow/blob/8d72537c6abf5a44103b57b9c2e22c14f5f49698/tensorflow/core/kernels/list_kernels.cc#L312)
  calls `std::vector.resize()` with the new size controlled by input given by the
  user, without checking that this input is valid. We have patched the issue in GitHub
  commit 8a6e874437670045e6c7dc6154c7412b4a2135e2. The fix will be included in TensorFlow
  We will also cherrypick this commit on TensorFlow, TensorFlow, and TensorFlow, as
  these are also affected and still in supported range."
date: "2021-08-18"
pubdate: "2021-08-12"
affected_range: ">=2.3.0,<2.3.4||>=2.4.0,<2.4.3||>=2.5.0,<=2.6.0"
fixed_versions:
- "2.3.4"
- "2.4.3"
affected_versions: "All versions starting from 2.3.0 before 2.3.4, all versions starting
  from 2.4.0 before 2.4.3, all versions starting from 2.5.0 up to 2.6.0"
not_impacted: "All versions before 2.3.0, all versions starting from 2.3.4 before
  2.4.0, all versions starting from 2.4.3 before 2.5.0, all versions after 2.6.0"
solution: "Upgrade to versions 2.3.4, 2.4.3 or above."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2021-37644"
cvss_v2: "AV:L/AC:L/Au:N/C:N/I:N/A:P"
cvss_v3: "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H"
uuid: "5523b550-8892-4766-86e9-2d3783e590f4"
