---
identifier: "CVE-2021-29544"
package_slug: "pypi/tensorflow"
title: "Improper Check for Unusual or Exceptional Conditions"
description: "TensorFlow is an end-to-end open source platform for machine learning.
  An attacker can trigger a denial of service via a `CHECK`-fail in `tf.raw_ops.QuantizeAndDequantizeV4Grad`.
  This is because the implementation(https://github.com/tensorflow/tensorflow/blob/95078c145b5a7a43ee046144005f733092756ab5/tensorflow/core/kernels/quantize_and_dequantize_op.cc#L162-L163)
  does not validate the rank of the `input_*` tensors. In turn, this results in the
  tensors being passes as they are to `QuantizeAndDequantizePerChannelGradientImpl`(https://github.com/tensorflow/tensorflow/blob/95078c145b5a7a43ee046144005f733092756ab5/tensorflow/core/kernels/quantize_and_dequantize_op.h#L295-L306).
  However, the `vec<T>` method, requires the rank to 1 and triggers a `CHECK` failure
  otherwise. The fix will be included in TensorFlow We will also cherrypick this commit
  on TensorFlow as this is the only other affected version."
date: "2021-05-18"
pubdate: "2021-05-14"
affected_range: "<=2.1.4||>=2.2.0,<=2.2.3||>=2.3.0,<=2.3.3||>=2.4.0,<=2.4.2"
fixed_versions:
- "2.5.0"
affected_versions: "All versions up to 2.1.4, all versions starting from 2.2.0 up
  to 2.2.3, all versions starting from 2.3.0 up to 2.3.3, all versions starting from
  2.4.0 up to 2.4.2"
not_impacted: "All versions after 2.1.4 before 2.2.0, all versions after 2.2.3 before
  2.3.0, all versions after 2.3.3 before 2.4.0, all versions after 2.4.2"
solution: "Upgrade to version 2.5.0 or above."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2021-29544"
cvss_v2: "AV:L/AC:L/Au:N/C:N/I:N/A:P"
cvss_v3: "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H"
uuid: "92ee6fe3-3b23-478e-94db-a560e0a63895"
