---
identifier: "CVE-2021-29547"
package_slug: "maven/org.tensorflow/parentpom"
title: "Out-of-bounds Read"
description: "TensorFlow is an end-to-end open source platform for machine learning.
  An attacker can cause a segfault and denial of service via accessing data outside
  of bounds in `tf.raw_ops.QuantizedBatchNormWithGlobalNormalization`. This is because
  the implementation(https://github.com/tensorflow/tensorflow/blob/55a97caa9e99c7f37a0bbbeb414dc55553d3ae7f/tensorflow/core/kernels/quantized_batch_norm_op.cc#L176-L189)
  assumes the inputs are not empty. If any of these inputs is empty, `.flat<T>()`
  is an empty buffer, so accessing the element at index 0 is accessing data outside
  of bounds. The fix will be included in TensorFlow We will also cherrypick this commit
  on TensorFlow, TensorFlow, TensorFlow and TensorFlow, as these are also affected
  and still in supported range."
date: "2021-05-18"
pubdate: "2021-05-14"
affected_range: "(,2.1.4],[2.2.0,2.2.3],[2.3.0,2.3.3],[2.4.0,2.4.2]"
fixed_versions: []
affected_versions: "All versions up to 2.1.4, all versions starting from 2.2.0 up
  to 2.2.3, all versions starting from 2.3.0 up to 2.3.3, all versions starting from
  2.4.0 up to 2.4.2"
not_impacted: ""
solution: "Unfortunately, there is no solution available yet."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2021-29547"
cvss_v2: "AV:L/AC:L/Au:N/C:N/I:N/A:P"
cvss_v3: "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H"
uuid: "db68f782-9673-4958-b4c0-d63dd1a5b2df"
